### ISSUE TITLE
Auto Suggest menu goes behind other components

### ISSUE THREAD

**Issue by prameetchakraborty** [silesky/react-native-autosuggest#2]
On typing, the auto-suggest menu gets hidden behind other components on the screen. Is there a fix for that? I have tried changing z-index but nothing happened.

**Comment by hossammourad** [comment]
@prameetchakraborty How did you fix that? I'm facing the same issue.

**Comment by prameetchakraborty** [comment]
@hos4m In the main javascript file, the listview has a "position : absolute" property which is unnecessary. You can either remove it or change the position to 'relative'. With that small change, other components will automatically get pushed below the auto-suggest menu.

So that fixes the issue :-)

**Comment by hossammourad** [comment]
@prameetchakraborty This fixed the issue, thank you!
