### ISSUE TITLE
Got 'undefined is not an object (evaluating '_react2.PropTypes.object')

### ISSUE THREAD

**Issue by jamesguan** [silesky/react-native-autosuggest#7]
Got 'undefined is not an object (evaluating '_react2.PropTypes.object') and not sure why? Tried to use just a basic AutoSuggest.

**Comment by silesky** [comment]
I will investigate. thanks for reporting this.

**Comment by silesky** [comment]
fixed https://github.com/silesky/react-native-autosuggest/commit/9ad5f7e1371422948d65493b58c959e38dd8d43f.

added the PropTypes dependency (only react ^15.5.10 is supported by the latest version).
